const propertiesOptions = [
  { id: 1, component: "operation", name: "Operación" },
  { id: 2, component: "property", name: "Propiedad" },
  { id: 3, component: "environments", name: "Cant. ambientes" },
  { id: 4, component: "bedrooms", name: "Cant. habitaciones" },
  { id: 5, component: "bathrooms", name: "Cant. baños" },
  { id: 6, component: "area", name: "Area" },
  { id: 7, component: "garage", name: "Cant. Garage" },
  { id: 8, component: "state", name: "Estado" },
  { id: 9, component: "availability", name: "Habilitado" },
  { id: 10, component: "name", name: "Nombre" },
  { id: 11, component: "description", name: "Descripción" },
  { id: 12, component: "price", name: "Precio" },
  {
    id: 13,
    component: "images",
    name: "Imagenes",
  },
  {
    id: 14,
    component: "address",
    name: "Dirección",
    moreOptions: [
      { id: 14.1, component: "province", name: "Provincia" },
      { id: 14.2, component: "zone", name: "Zona" },
      { id: 14.3, component: "street", name: "Calle" },
      { id: 14.4, component: "postalCode", name: "Cod. Postal" },
    ],
  },
  {
    id: 15,
    component: "services",
    name: "Servicios",
    moreOptions: [
      { id: 15.1, component: "runningWater", name: "Agua corriente Central" },
      { id: 15.2, component: "airConditioning", name: "Aire acondicionado" },
      { id: 15.3, component: "balcony", name: "Balcón" },
      { id: 15.4, component: "kitchen", name: "Cocina" },
      { id: 15.5, component: "parking", name: "Estacionamiento" },
      { id: 15.6, component: "gas", name: "Gas" },
      { id: 15.7, component: "gym", name: "Gimnasio" },
      { id: 15.8, component: "laundry", name: "Lavadero" },
      { id: 15.9, component: "light", name: "Electricidad" },
      { id: 15.10, component: "petfriendly", name: "Apto mascotas" },
      { id: 15.11, component: "houseMaid", name: "Mucama" },
      { id: 15.12, component: "grill", name: "Parrilla" },
      { id: 15.13, component: "yard", name: "Patio" },
      { id: 15.14, component: "swimmingpool", name: "Piscina" },
      { id: 15.15, component: "security", name: "Seguridad 24hs" },
      { id: 15.16, component: "waterHeater", name: "Termotanque" },
      { id: 15.17, component: "dressingRoom", name: "Vestidor" },
      { id: 15.18, component: "wifi", name: "Internet" },
    ],
  },
];

export default propertiesOptions;
