const propertiesOptions = [
  { id: 1, component: "operation", name: "Operación" },
  { id: 2, component: "property", name: "Propiedad" },
  { id: 3, component: "environments", name: "Cant. ambientes" },
  { id: 4, component: "bedrooms", name: "Cant. habitaciones" },
  { id: 5, component: "bathrooms", name: "Cant. baños" },
  { id: 6, component: "area", name: "Area" },
  { id: 7, component: "garage", name: "Cant. Garage" },
  { id: 8, component: "state", name: "Estado" },
  { id: 9, component: "availability", name: "Habilitado" },
  { id: 10, component: "name", name: "Nombre" },
  { id: 11, component: "description", name: "Descripción" },
  { id: 12, component: "price", name: "Precio" },
  {
    id: 13,
    component: "images",
    name: "Imagenes",
  },
  {
    id: 14,
    component: "address",
    name: "Dirección",
    moreOptions: [
      { id: 12.1, component: "country", name: "País" },
      { id: 12.2, component: "province", name: "Provincia" },
      { id: 12.3, component: "zone", name: "Zona" },
      { id: 12.4, component: "street", name: "Calle" },
      { id: 12.5, component: "postalCode", name: "Cod. Postal" },
    ],
  },
  {
    id: 15,
    component: "services",
    name: "Servicios",
    moreOptions: [
      { id: 13.1, component: "airConditioning", name: "Aire acondicionado" },
      { id: 13.2, component: "runningWater", name: "Agua corriente" },
      { id: 13.3, component: "pavement", name: "Pavimento" },
      { id: 13.4, component: "waterHeater", name: "Termotanque" },
      { id: 13.5, component: "light", name: "Luz" },
      { id: 13.6, component: "kitchen", name: "Cocina" },
      { id: 13.7, component: "sewageDrain", name: "Drenaje" },
      { id: 13.8, component: "balcony", name: "Balcón" },
      { id: 13.9, component: "laundry", name: "Lavarropas" },
      { id: 13.10, component: "yard", name: "Patio" },
      { id: 13.11, component: "dressingRoom", name: "Vestidor" },
    ],
  },
];

export default propertiesOptions;
